server:
  port: 10085
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:  # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
